Reorganize js and add groundwork for jest tests
ucfopen/normal-distribution-calculator-materia-widget pull request #4
Opened 2019-03-28 00:10 UTC by iturgeon

2019-03-28 17:23 UTC, FrenjaminBanklin requested changes
The tests pass and the widget runs, aside from the problem with the demo.

2019-03-28 17:23 UTC, FrenjaminBanklin commented on src/demo.json
> +    "data": {}
Widget instances won't save qsets if the `data` property is empty - something has to be in here to avoid problems down the line, at least for now.

2019-04-01 17:46 UTC, zachberry requested changes

2019-04-01 17:46 UTC, zachberry commented on src/graph.js
> +		context.translate(5, this.canvas.height - this.getPixelY((this.maxY + this.minY) / 2));
```suggestion
		context.translate(10, this.canvas.height - this.getPixelY((this.maxY + this.minY) / 2));
```

Unrelated to this PR really, but noticed the f(x) was being chopped off, and this fixes it

2019-04-01 17:47 UTC, zachberry commented on src/graph.js
> +		context.translate(5, this.canvas.height - this.getPixelY((this.maxY + this.minY) / 2));
Otherwise LGTM

2019-04-01 19:36 UTC, clpetersonucf approved these changes
This diff is a chonker, but functionally everything appears to work.

2019-04-02 14:43 UTC, FrenjaminBanklin approved these changes
MWDK works, widget builds/installs to Materia properly, tests run.

Looks good.

2019-04-02 14:51 UTC, merged